### ISSUE TITLE
可否不显示包含H3及H3更小的标题的提示，如图

### ISSUE THREAD

**Issue by JungwooJava** [Soanguy/typora-theme-autumnus#14]
![image](https://user-images.githubusercontent.com/21309754/106727472-7c0e7c00-6646-11eb-8bb4-fc980a9905f1.png)

**Comment by Higurashi-kagome** [comment]
可尝试删除主题文件中的如下样式：

```CSS
#write h3::before {
	content: "H3";
}

#write h4::before {
	content: "H4";
}

#write h5::before {
	content: "H5";
}

#write h6::before {
	content: "H6";
}
```

并添加：

```CSS
#write h3::before,
#write h4::before,
#write h5::before,
#write h6::before {
	content: none;
} 
```
