### ISSUE TITLE
[Bug report] Fluence 下查找框无法正常显示

### ISSUE THREAD

**Issue by Higurashi-kagome** [Soanguy/typora-theme-autumnus#4]
Hi👋!

我发现 Fluence 主题下的查找框被遮住了。

<details>
			<summary>Gif</summary>

  ![input](https://user-images.githubusercontent.com/51501079/100529502-2cb16700-3223-11eb-997e-86ccf646cce6.gif)

</details>

似乎与这部分代码有关：

```CSS
#write:after,
#typora-sidebar::after
{
  content: "";
  background: rgba(221, 221, 221, 0.5);
  backdrop-filter: saturate(180%) blur(20px);
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  z-index: -99;
  min-height: 100%;
  border-radius: 5px;
}
```
